# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Note-App.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 605)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.primary_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.primary_layout.setContentsMargins(0, 0, 0, 0)
        self.primary_layout.setObjectName("primary_layout")
        self.tree_widget = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_widget.sizePolicy().hasHeightForWidth())
        self.tree_widget.setSizePolicy(sizePolicy)
        self.tree_widget.setObjectName("tree_widget")
        self.tree_widget.headerItem().setText(0, "1")
        self.primary_layout.addWidget(self.tree_widget)
        self.work_area = QtWidgets.QVBoxLayout()
        self.work_area.setObjectName("work_area")
        self.main_text_area = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.main_text_area.setObjectName("main_text_area")
        self.work_area.addWidget(self.main_text_area)
        self.status_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.status_line.setReadOnly(True)
        self.status_line.setObjectName("status_line")
        self.work_area.addWidget(self.status_line)
        self.primary_layout.addLayout(self.work_area)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Secure Note App"))
