
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './new_note_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(392, 80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cancel_button)
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setObjectName("create_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.create_button)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lineEdit)

        self.retranslateUi(Dialog)
        self.lineEdit.returnPressed.connect(self.create_button.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Note"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.create_button.setText(_translate("Dialog", "Create"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "New note name"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './note_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 612)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setMinimumSize(QtCore.QSize(798, 564))
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.tree_widget = QtWidgets.QTreeWidget(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_widget.sizePolicy().hasHeightForWidth())
        self.tree_widget.setSizePolicy(sizePolicy)
        self.tree_widget.setObjectName("tree_widget")
        self.tree_widget.headerItem().setText(0, "Files")
        self.tree_widget.header().setVisible(True)
        self.gridLayout.addWidget(self.tree_widget, 0, 0, 1, 1)
        self.main_text_area = QtWidgets.QPlainTextEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_text_area.sizePolicy().hasHeightForWidth())
        self.main_text_area.setSizePolicy(sizePolicy)
        self.main_text_area.setObjectName("main_text_area")
        self.gridLayout.addWidget(self.main_text_area, 0, 1, 1, 1)
        self.status_line = QtWidgets.QLineEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_line.sizePolicy().hasHeightForWidth())
        self.status_line.setSizePolicy(sizePolicy)
        self.status_line.setReadOnly(True)
        self.status_line.setObjectName("status_line")
        self.gridLayout.addWidget(self.status_line, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_button = QtWidgets.QPushButton(self.central_widget)
        self.new_button.setObjectName("new_button")
        self.horizontalLayout.addWidget(self.new_button)
        self.delete_button = QtWidgets.QPushButton(self.central_widget)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.save_button = QtWidgets.QPushButton(self.central_widget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Secure Note App"))
        self.new_button.setText(_translate("MainWindow", "New"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.save_button.setText(_translate("MainWindow", "Save"))
